export default{
    abbigliamento: [
        {
            _id:'1',
            nome: 'full zip tshirt ',
            categorie: 'shirts',
            image: '/images/abbigliamento1.jpg',
            price: 60,
            marca: 'nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            nome: 'Pantaloni',
            categorie: 'pantaloni',
            image: 'images/pantalone.jpg',
            price: 60,
            marca: 'LV',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            nome: 'gonna',
            categorie: 'gonne',
            image: 'images/gonna.jpg',
            price: 60,
            marca: 'gucci',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            nome: 'giacca',
            categorie: 'giacca',
            image: 'images/giacca2.jpg',
            price: 60,
            marca: 'adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            nome: 'smoking',
            categorie: 'abiti',
            image: 'images/smoking.jpg',
            price: 60,
            marca: 'adidas',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
};